timeF_2/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('times/', include('times.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

times/urls.py
from django.urls import path, re_path

from .import views

app_name = 'times'
urlpatterns = [
    path('', views.YearMonthListView.as_view(), name="year_months"),
    path('year_month/create/', views.YearMonthCreate.as_view(), name='year_month_create'),
    path('year_month/<int:pk>/update/',
         views.YearMonthUpdate.as_view(), name='year_month_update'),
    path('year_month/<int:pk>/delete/',
         views.YearMonthDelete.as_view(), name='year_month_delete'),
    path('month_detail/<int:pk>',
         views.MonthDetailView.as_view(), name="month_detail"),
]

# the url of detail for week and day
urlpatterns += [
    path('year_month/<int:pk>/number/<int:number>',
         views.WeekDetailView.as_view(), name="week_detail"),
    path('days/<int:pk>/detail/', views.DayDetailView.as_view(), name="day_detail"),
    path('year_month/<int:pk>/generate_days/<int:number>',
         views.generate_days, name='generate_days'),
]

# url for category and estimates
urlpatterns +=[
    path('year_month/<int:pk>/number/<int:number>/estimates_create',
         views.EstimateCreate.as_view(), name='estimates_create'),
    path('year_month/<int:pk>/number/<int:number>/plan_infos',
         views.EstimateInfo.as_view(), name='plan_infos'),
    path('year_month/<int:ym_pk>/number/<int:number>/time_plans/<int:pk>/update/',
         views.EstimateUpdate.as_view(), name='estimate_update'),
    path('categories/<int:ym_pk>/<int:number>/<str:key>/',
         views.CategoryDetail.as_view(), name='ctime_entry'),
]

times/models.py
from django.db.models import Sum
from django.db import models
from django.contrib.auth.models import User


class YearMonth(models.Model):
    year = models.CharField(max_length=4)
    month = models.CharField(max_length=2)

    @property
    def y_m(self):
        return f'{self.year} - {self.month}'

    def __str__(self):
        return self.y_m
        


class Day(models.Model):
    year_month = models.ForeignKey(
        'YearMonth', on_delete=models.CASCADE, null=True)
    recorder = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True)
    day_name = models.CharField(max_length=200)
    time_entry = models.DecimalField(decimal_places=2, max_digits=6, blank=True)
    pub_date = models.DateField()
    begin_time = models.TimeField()

    def __str__(self):
        return self.day_name


class Category(models.Model):
    cname = models.CharField(max_length=200)
    alias = models.CharField(max_length=200)

    def __str__(self):
        return self.cname

    @property
    def time_entry(self):
        subtotal = self.item_set.all().aggregate(Sum('duration'))
        return subtotal.get('duration__sum')

class TimePlan(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    # the unit of duration is mintue
    duration = models.IntegerField()
    begin_date = models.DateField()
    end_date = models.DateField()

    def __str__(self):
        return f'{self.begin_date}~{self.end_date}#{self.category.cname}-estimate'

class Item(models.Model):
    item_name = models.CharField(max_length=200)
    duration = models.DecimalField(decimal_places=2, max_digits=64)
    day = models.ForeignKey(Day, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    pub_date = models.DateField()
    year_month = models.ForeignKey(
        'YearMonth', on_delete=models.SET_NULL, null=True)

    def cname(self):
        return self.category.cname

    def __str__(self):
        return self.item_name

times/views.py
from django.db.models import Sum
import numpy as np
from chartjs.views.lines import BaseLineChartView
from datetime import datetime, date
import re, os, time, re
import codecs as cs
from bs4 import BeautifulSoup
from django.shortcuts import get_object_or_404, render

from django.http import HttpResponseRedirect
from django.template import loader, Library

from .models import Day, Item, YearMonth, Category, TimePlan

# import the current file settings
from .settings import DIR_PATH
# for create object
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from django.views import generic
from django.urls import reverse, reverse_lazy
# for read files
from django.core.files import File

import glob


class YearMonthListView(generic.ListView):
    model = YearMonth


class YearMonthCreate(CreateView):
    model = YearMonth
    fields = '__all__'
    success_url = reverse_lazy('times:year_months')


class YearMonthUpdate(UpdateView):
    model = YearMonth
    fields = '__all__'
    success_url = reverse_lazy('times:year_months')


class YearMonthDelete(DeleteView):
    model = YearMonth
    success_url = reverse_lazy('times:year_months')


class MonthDetailView(generic.DetailView):
    model = YearMonth

    def get_context_data(self, **kwargs):
        context = super(MonthDetailView, self).get_context_data(**kwargs)
        context['day_list'] = Day.objects.filter(year_month=self.object).extra(
            select={'day_number': 'CAST(day_name AS INTEGER)'}
        ).order_by('day_number')
        
        return context


class EstimateCreate(CreateView):
    model = TimePlan
    fields = '__all__'

    def get_initial(self):
        initial = super(EstimateCreate, self).get_initial()
        yearmonth = YearMonth.objects.get(pk=self.kwargs['pk'])
        bday, eday = which_week(self.kwargs['number'])
        begin_date, end_date = b_e_date(
            yearmonth.year, yearmonth.month, bday, eday)
        initial.update({'begin_date': begin_date,
                        'end_date': end_date})
        return initial

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.save()
        pk, number = self.kwargs['pk'], self.kwargs['number']
        return HttpResponseRedirect(reverse('times:week_detail', args=[pk, number]))


class EstimateInfo(generic.DetailView):
    model = YearMonth
    template_name = 'times/time_plans.html'

    def get_context_data(self, **kwargs):
        begin_number, end_number = which_week(self.kwargs['number'])
        begin_date = b_e_date(self.object.year, self.object.month, begin_number, end_number)[0]
        context = super(EstimateInfo, self).get_context_data(**kwargs)
        context['time_plans'] = TimePlan.objects.filter(begin_date=begin_date)
        context['params'] = {'pk': self.object.pk,
                             'number': self.kwargs['number']}

        return context

class EstimateUpdate(UpdateView):
    model = TimePlan
    fields = '__all__'

    def get_success_url(self):
        return reverse_lazy('times:week_detail', kwargs={'pk': self.kwargs['ym_pk'], 'number': self.kwargs['number']})


class CategoryDetail(generic.ListView):
    model = Category

    def get_context_data(self, **kwargs):
        begin_number, end_number = which_week(self.kwargs['number'])
        y_m = YearMonth.objects.get(pk=self.kwargs['ym_pk'])
        begin_date, end_date = b_e_date(
            y_m.year, y_m.month, begin_number, end_number)
        context = super(CategoryDetail, self).get_context_data(**kwargs)
        context['category_list'] = Category.objects.filter(
            alias=self.kwargs['key'])
        context['params'] = {'pk': y_m.pk,
                             'number': self.kwargs['number'],
                             'begin_date': begin_date,
                             'end_date': end_date,
                             }

        return context

def generate_days(request, pk, **kwargs):
    # statistic time for this function
    t_1 = datetime.now()

    recorder = request.user
    year_month = YearMonth.objects.get(pk=pk)
    yy, mm = int(year_month.year), int(year_month.month)

    # read files the type of html on local
    number = kwargs['number']
    files = obtain_files(yy, mm, number)

    if len(files) <= 0:
        return HttpResponseRedirect(reverse('times:month_detail', args=[pk]))

    for idx_f, file in enumerate(files):
        file_name = os.path.basename(file)
        params = dict()
        grant_time = 0

        if file_name != 'index.html':
            file_content = cs.open(file, 'r', 'utf-8').read()
            document = BeautifulSoup(file_content, 'html.parser').get_text()
            reset_doc = document.split('。')

            # generate day by the head information
            # or generate items by the body information
            for idx, item_text in enumerate(reset_doc):
                if idx == 0:
                    month, dd, hh, mi = re.findall(r'\d+', item_text)
                    try: 
                        Day.objects.filter(day_name=f'{dd}/{mm}/{yy}').delete()
                    except:
                        print('Dose Not Exist object')

                    if int(month) == mm:
                        params['day_name'] = f'{dd}/{mm}/{yy}'
                        params['begin_time'] = datetime.strptime(
                            f'{yy}/{mm}/{dd} {hh}:{mi}', '%Y/%m/%d %H:%M').strftime("%H:%M")
                        params['recorder'] = recorder
                        params['year_month'] = year_month
                        params['pub_date'] = datetime.strptime(
                            f'{yy}/{mm}/{dd}', '%Y/%m/%d')
                        day = Day(**params)
                    else:
                        return HttpResponseRedirect(reverse('times:month_detail', args=[pk]))
                else:
                    try:
                        *item_name, duration = item_text.replace('分钟', '').split('：')
                        item_name = '#'.join(item_name)
                        category = classify(item_name)
                        item = Item(item_name=item_name, duration=duration, day=day,
                                    year_month=year_month, category=category, pub_date=day.pub_date)
                        item.save()
                        grant_time += int(duration)
                    except:
                        item_text
                day.time_entry = grant_time
                day.save()
    t_2 = datetime.now() - t_1
    print(t_2)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def obtain_files(yy, mm, number):
    begin_day, end_day = which_week(number)
    dir_path = DIR_PATH % (yy, mm)
    files = [file for file in glob.glob(dir_path) if "index.html" not in file]
    return sorted(files, key=file_title)[begin_day:end_day]


def file_title(filename):
    pattern = re.compile(r'(\d+)')
    return int(pattern.findall(filename)[-1])

def classify(name):
    pre_name = name.split('@')[0]
    category = Category.objects.filter(cname=pre_name)
    if not category.exists() and pre_name:
        category = Category(cname=pre_name, alias=pre_name)
        category.save()

    return Category.objects.get(cname=pre_name)

class DayDetailView(generic.DetailView):
    model = Day
    template_name = 'times/day_detail.html'
    

class WeekDetailView(generic.DetailView):
    model = YearMonth
    template_name = 'times/week_detail.html'

    def get_context_data(self, **kwargs):
        begin_day, end_day = which_week(self.kwargs['number'])

        context = super(WeekDetailView, self).get_context_data(**kwargs)
        context['number'] = self.kwargs['number']
        context['day_list'] = Day.objects.filter(year_month=kwargs['object']).extra(
            select={'day_number': 'CAST(day_name AS INTEGER)'}
        ).order_by('day_number')[begin_day:end_day]
        context['subtotals'], context['estimates'] = subtotals(
            kwargs['object'].year, kwargs['object'].month, begin_day, end_day)
        return context


def subtotals(yy, mm, bday, eday):
    begin_date, end_date = b_e_date(yy, mm, bday, eday)
    results = {}
    estimates = {}
    clist = Category.objects.all().values_list('alias', flat=True)
    for alias in set(list(clist)):
        for c in Category.objects.filter(alias=alias):
            items = c.item_set.filter(
                pub_date__range=[begin_date, end_date])
            results[alias] = results.get(
                alias, 0) + sum(items.values_list('duration', flat=True))
            plans = c.timeplan_set.filter(begin_date=begin_date).distinct()
            estimates[alias] = estimates.get(
                alias, 0) + sum(plans.values_list('duration', flat=True))

    results = {k: v for k, v in sorted(
        results.items(), key=lambda item: item[1], reverse=True)}
    estimates = {k: v for k, v in sorted(
        estimates.items(), key=lambda item: item[1], reverse=True)}

    return results, estimates

# generate begin and end date
def b_e_date(yy, mm, bday, eday):
    yy, mm, bday, eday= int(yy), int(mm), int(bday+1), int(eday)
    begin_date = date(yy, mm, bday)
    try:
        end_date = date(yy, mm, eday)
    except:
        end_date = date(yy, mm, eday-1)

    return begin_date, end_date

def which_week(number):
    if int(number) == 0:
        return 0, 7
    elif int(number) == 1:
        return 7, 14
    elif int(number) == 2:
        return 14, 21
    elif int(number) == 3:
        return 21, 31
    elif int(number) == 6:
        return 0, 31

times/templates/times/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Time Friend</title>

    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  </head>
  <body>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-8">
          <hr class="mt-0 mb-4">
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

times/templates/times/category_list.html
{% extends "base_generic.html" %}
{% load filters_extras %}
{% load mathfilters %}

{% block content %}
  <h4>Categories List</h4>
  <button class="float-right btn btn-sm btn-outline-success" type="button" onclick="history.back();">返回</button>
  {% if category_list %}
    {% for category in category_list %}
        {% items_by_date_range category params|get_item:'begin_date' params|get_item:'end_date' as items %}
        {% if items %}
            {% with total=items|summary %}
            {{category.cname}}:{{total}}
                <ul>
                    {% for name, value in items.items %}
                        <br>
                        {{name}}
                        <div class="progress">
                            <div class="progress-bar bg-info" role="progressbar" style="width:{{value|div:total|mul:100}}%;" aria-valuemin="0" aria-valuemax="100">
                                <a>{{ value }}</a>
                            </div>
                        </div>
                    {% endfor %}
                </ul>
            {% endwith %}
        {% endif %}
    {% endfor %}
  {% else %}
    <p>There are no categoriest in the Time Machine.</p>
  {% endif %}       
{% endblock %}

times/templates/times/day_detail.html
{% extends "base_generic.html" %}
{% load filters_extras %}

{% block content %}
    <h1>{{ day.day_name|reverse  }}</h1>
    <p><strong>total: {{ day.time_entry }} minutes </strong></p>
    <ul>
    {% for item in day.item_set.all %}
        <li>{{ item.item_name }}: {{item.duration}}</li>
    {% endfor %}
    </ul>
{% endblock %}

times/templates/times/detail.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>{{ day.day_name }}</h1>
    <ul>
    {% for item in day.item_set.all %}
        <li>{{ item.item_name }}: {{item.duration}}</li>
    {% endfor %}
    </ul>
{% endblock %}

times/templates/times/time_plans.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}
{% load filters_extras %}

{% block content %}
    {% if time_plans %}
        <ul>
        {% for plan in time_plans %}
            <li><a href="{% url 'times:estimate_update' params|get_item:'pk' params|get_item:'number' plan.pk %}">{{ plan.category.cname }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No days are available.</p>
    {% endif %}
{% endblock %}

{% block filter %}
    <div class="card" style="width: 18rem;">
        <div class="card-header">
            Filter By Week
        </div>
        <ul class="list-group list-group-flush">
            {% for i in '0123' %}
                <li class="list-group-item"><a href="{% url 'times:week_detail' params|get_item:'pk' i%}">第{{i|add:1}}周</a></li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

times/templates/times/timeplan_form.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form|crispy }}
    </table>
    <input type="submit" value="生成" class="btn btn-outline-success">
  </form>
{% endblock %}

times/templates/times/week_detail.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}
{% load filters_extras %}
{% load mathfilters %}


{% block content %}
    <a href="{% url 'times:generate_days' yearmonth.pk number %}" class="btn btn-sm btn-primary float-right">Generate Days</a>
    {% if day_list %}
        <ul>
        {% for day in day_list %}
            <li><a href="{% url 'times:day_detail' day.pk%}">{{ day.day_name|reverse }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No days are available.</p>
    {% endif %}

    <hr>

    <a href="{% url 'times:plan_infos' yearmonth.pk number %}" class="btn btn-sm btn-success float-right">Edit Plan</a>
    <a href="{% url 'times:estimates_create' yearmonth.pk number %}" class="btn btn-sm btn-info float-right">Generate Plan</a>
    <br>
    <ul>
    {% with total=subtotals|summary  %}
        <h5>本周: {{total}} 分钟 </h5>
        <br>
        {% for key, value in subtotals.items %}
            {% with a=value b=estimates|get_item:key %}
                {% if value > 0 %}
                    {{key}} : {{value}}
                    {% if estimates|get_item:key > 0 %}
                        <div class="progress">
                            <div class="progress-bar bg-info" role="progressbar" style="width:{{a|div:b|mul:100}}%;" aria-valuemin="0" aria-valuemax="100">
                                <a href="{% url 'times:ctime_entry' yearmonth.pk number key %}" style="color:white">
                                    {{value|div:total|mul:100|floatformat:2}}({{a|div:b|mul:100|floatformat:2}})~~
                                    {% if b|sub:a >= 0 %}
                                        L {{b|sub:a}}
                                    {% else %}
                                        M {{a|sub:b}}
                                    {% endif %}
                                </a>
                            </div>
                        </div>
                    {% else %}
                        <div class="progress">
                            <div class="progress-bar progress-bar-striped progress-bar-animated bg-warning" role="progressbar" style="width:{{value|div:total|mul:100}}%;" aria-valuemin="0" aria-valuemax="100">
                                <a href="{% url 'times:ctime_entry' yearmonth.pk number key %}" style="color:white">
                                    {{value|div:total|mul:100|floatformat:2}}
                                </a>
                            </div>
                        </div>
                    {% endif %}
                {% elif value <= 0 and b > 0 %}
                    {{key}} : {{0}}
                    <div class="progress">
                        <div class="progress-bar progress-bar-striped progress-bar-animated bg-warning" role="progressbar" style="width:0%;" aria-valuemin="0" aria-valuemax="100">
                            <a>{{b}}</a>
                        </div>
                    </div>
                {% endif %}
            {% endwith %}
        {% endfor %}
    {% endwith %}
    </ul>

{% endblock %}

{% block filter %}
    <div class="card" style="width: 18rem;">
        <div class="card-header">
            Filter By Week
        </div>
        <ul class="list-group list-group-flush">
            {% for i in '0123' %}
                <li class="list-group-item"><a href="{% url 'times:week_detail' yearmonth.pk i%}">第{{i|add:1}}周</a></li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

times/templates/times/yearmonth_confirm_delete.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}

{% block content %}

<h1>Delete Year Month</h1>

<p>Are you sure you want to delete the year_month: {{ yearmonth }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

times/templates/times/yearmonth_detail.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}
{% load filters_extras %}

{% block content %}
    <a href="{% url 'times:generate_days' yearmonth.pk 6 %}" class="btn btn-sm btn-primary float-right">Generate Days</a>
    {% if day_list %}
        <ul>
        {% for day in day_list %}
            <li><a href="{% url 'times:day_detail' day.pk%}">{{ day.day_name|reverse }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No days are available.</p>
    {% endif %}
{% endblock %}

{% block filter %}
    <div class="card" style="width: 18rem;">
        <div class="card-header">
            Filter By Week
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item"><a href="{% url 'times:week_detail' yearmonth.pk 0%}">1st</a></li>
            <li class="list-group-item"><a href="{% url 'times:week_detail' yearmonth.pk 1%}">2nd</a></li>
            <li class="list-group-item"><a href="{% url 'times:week_detail' yearmonth.pk 2%}">3rd</a></li>
            <li class="list-group-item"><a href="{% url 'times:week_detail' yearmonth.pk 3%}">4th</a></li>
        </ul>
    </div>
{% endblock %}

times/templates/times/yearmonth_form.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form|crispy }}
    </table>
    <input type="submit" value="生成" class="btn btn-outline-success">
  </form>
{% endblock %}

times/templates/times/yearmonth_list.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <h1>Year Month List</h1>
  <a href="{% url 'times:year_month_create' %}" class="btn btn-sm btn-primary float-right">New Year Month</a>
  {% if yearmonth_list %}
  <ul>
    {% for year_month in yearmonth_list %}
      <li>
        <a href="{% url 'times:month_detail' year_month.pk %}">{{ year_month.year }}-{{ year_month.month }}
        <a href="{% url 'times:year_month_delete' year_month.pk %}" class="btn btn-sm btn-danger">删除</a>
      </li>
      <br>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no year_months in the Time Machine.</p>
  {% endif %}       
{% endblock %}